### PR TITLE
Alibi

### PR DESCRIPTION
**Pull request by RaymondLi0**

### CODE REVIEW

**Comment by RaymondLi0** [comment]
The renaming of `megatron/model/enums.py → megatron/enums.py` makes it impossible to load models trained with the main branch. Is this refactoring necessary, or would it be possible to revert this renaming @bigximik  ?

**Comment by bigximik** [comment]
is it only `AttnMaskType` that causes the trouble? I think we can revert it. But we need `PositionEmbeddingType`.

**Comment by RaymondLi0** [comment]
We can keep all of these, but putting them back into `megatron/model/enums.py` should fix the issue

**Comment by bigximik** [comment]
Moved enums back and fixed circular import

**Comment by RaymondLi0** [comment]
Great work! I think this can be merged now :)

**Pull request merged**
